language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t chulgs15/react-fullstack-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true chulgs15/react-fullstack-app npm test

after_success:
  - docker build -t chulgs15/docker-frontend ./frontend
  - docker build -t chulgs15/docker-backend ./backend
  - docker build -t chulgs15/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push chulgs15/docker-frontend
  - docker push chulgs15/docker-backend
  - docker push chulgs15/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-fullstack-app"
  env: "Dockerfullstackapp-env "
  bucket_name: elasticbeanstalk-us-east-2-267929877047
  bucket_path: "docker-fullstack-app"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_ACCESS_SECRET_KEY
